### ISSUE TITLE
Pagination is out of date relative to Front's API

### ISSUE THREAD

**Issue by oneeman** [resin-io-modules/front-sdk#14]
Thank you for this very nice library!

I've noticed that for pagination it's using a parameter called `page` which is supposed to be a number.  The front API currently uses a parameter called `page_token` (see for example https://dev.frontapp.com/#update-teammate ).  It's a long hexadecimal string.  I'm assuming that the API has changed since this library was written.

I worked around this by monkey-patching the API method I needed to use `[q:page_token:limit]` rather than `[q:page:limit]`, but I thought I would bring it to your attention.

**Comment by hedss** [comment]
@oneeman Thank you very much for bringing this to our attention, it does appear the pagination functionality has now changed.
